version: '3.9'
services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginxDeb/
    env_file:
      - .env
    ports:
      - 443:443
    networks:
      - web
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
  
  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/
    env_file:
      - .env
    expose:
      - "9000:9000"
    networks:
      - web
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
  
  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/
    env_file:
      - .env
    expose:
      - "3306:3306"
    networks:
      - web
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql

networks:
  web:
    driver: bridge



volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
