version: '3.9'
services:
  -nginx:
    container_name: nginx
    build: ./nginxDeb
    ports:
      - "443:443"
    networks:
      - web
    depends_on:
      - wordpress
    restart: on_failure
  
  -wordpress:
    container_name: wordpress
    build: ./wordpress
    expose:
      - "9000:9000"
    networks:
      - web
    depends_on:
      - mariadb
    restart: on_failure
  
  -mariadb:
    container_name: mariadb
    build: ./mariadb
    expose:
      - "3306:3306"
    networks:
      - web
    restart: on_failure
